# Generated by Django 3.0.6 on 2020-05-26 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('stock', models.IntegerField()),
                ('image_url', models.CharField(max_length=2083)),
            ],
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
